# Generated by Django 3.2.22 on 2023-11-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('pw', models.CharField(max_length=50)),
                ('group', models.IntegerField(default=0)),
                ('is_studying_now', models.BooleanField(default=False)),
                ('stime_daily', models.TimeField()),
                ('stime_weekly', models.TimeField()),
                ('stime_monthly', models.TimeField()),
                ('stime_total', models.TimeField()),
            ],
        ),
    ]
