# Generated by Django 3.2.22 on 2023-11-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stime_daily',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stime_monthly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stime_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='stime_weekly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.EmailField(max_length=200),
        ),
    ]
