# Generated by Django 3.2.22 on 2023-11-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_user_pw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pw',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
